In [28]:
import pandas as pd

log = pd.read_csv('visit_log.csv', sep=';')

In [29]:
log.head()

,timestamp,visit_id,url,region,user_id,traffic_source
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex

In [30]:
log.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18938 entries, 0 to 18937
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       18938 non-null  int64
 1   visit_id        18938 non-null  object
 2   url             18938 non-null  object
 3   region          18938 non-null  object
 4   user_id         18938 non-null  object
 5   traffic_source  18938 non-null  object
dtypes: int64(1), object(5)
memory usage: 887.8+ KB

In [31]:
#Фильтрация с помощью loc
#Фильтр на строки : фильтр на столбцы
# : - выбор всех значений
log.loc[:,['visit_id', 'url']].head()

     visit_id                                 url
0  e3b0c44298  https://host.ru/3c19b4ef7371864fa3
1  6e340b9cff  https://host.ru/c8d9213a31839f9a3a
2  96a296d224  https://host.ru/b8b58337d272ee7b15
3  709e80c884  https://host.ru/b8b58337d272ee7b15
4  df3f619804  https://host.ru/b8b58337d272ee7b15

In [32]:
#Фильтр на столбцы и строки

log.loc[log['region'] == 'Russia',['visit_id', 'url','region']].sample(10)

         visit_id                                 url  region
15351  f86f67c25c  https://host.ru/b8b58337d272ee7b15  Russia
18316  0d11f0226e  https://host.ru/05e41944dd85a900a6  Russia
15588  a36fd719fe  https://host.ru/6fda01ec57f23abc9e  Russia
5366   6ae5d7fde0  https://host.ru/8e88d4703848cc0ec4  Russia
1035   6444f999a1  https://host.ru/c8d9213a31839f9a3a  Russia
13107  37375743c8  https://host.ru/9010367b0b48d2f1b9  Russia
170    d07bdfd8af  https://host.ru/8e88d4703848cc0ec4  Russia
16140  560a80e996  https://host.ru/fd32c3d2de55949865  Russia
4533   8df2ac8f30  https://host.ru/53b1649b8344e663e9  Russia
5326   d650d39662  https://host.ru/ae8a036d7f44d0bcd9  Russia

In [33]:
#Фильтрация столбцов с помощью номера
log.iloc[:,[1,2]].head()

     visit_id                                 url
0  e3b0c44298  https://host.ru/3c19b4ef7371864fa3
1  6e340b9cff  https://host.ru/c8d9213a31839f9a3a
2  96a296d224  https://host.ru/b8b58337d272ee7b15
3  709e80c884  https://host.ru/b8b58337d272ee7b15
4  df3f619804  https://host.ru/b8b58337d272ee7b15

In [34]:
#Выбор по строкам и столбцам
log.iloc[10:20,2:4].head()

                                   url   region
10  https://host.ru/a5dda93e70318570c0    India
11  https://host.ru/c8d9213a31839f9a3a  Ukraine
12  https://host.ru/8e88d4703848cc0ec4   Russia
13  https://host.ru/3004a8273caeef2867    China
14  https://host.ru/05e41944dd85a900a6  Belarus

In [35]:
log.iloc[:,list(range(-1,-3,-1))].head()

  traffic_source     user_id
0         yandex  b1613cc09f
1         direct  4c3ec14bee
2         yandex  a8c40697fb
3         yandex  521ac1d6a0
4         yandex  d7323c571c

In [36]:
#Изменить порядок столбцов
log.iloc[:,list(range(-1,-len(log.keys()),-1))].head()

,traffic_source,user_id,region,url,visit_id
0,yandex,b1613cc09f,Russia,https://host.ru/3c19b4ef7371864fa3,e3b0c44298
1,direct,4c3ec14bee,Russia,https://host.ru/c8d9213a31839f9a3a,6e340b9cff
2,yandex,a8c40697fb,Russia,https://host.ru/b8b58337d272ee7b15,96a296d224
3,yandex,521ac1d6a0,Russia,https://host.ru/b8b58337d272ee7b15,709e80c884
4,yandex,d7323c571c,Russia,https://host.ru/b8b58337d272ee7b15,df3f619804

In [37]:
#Фильтр с помощью loc

log.loc[log['region'] == 'Russia'].head()

,timestamp,visit_id,url,region,user_id,traffic_source
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex

In [38]:
#Добавление cстолбца
log.loc[:,'new'] = 1

In [39]:
log

,timestamp,visit_id,url,region,user_id,traffic_source,new
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,1
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,1
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,1
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,1
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,1
...,...,...,...,...,...,...,...
18933,1550094288,57e5ba8560,https://host.ru/c2382eb3d6afc8d0f3,Belarus,98b19810d0,paid,1
18934,1550094296,6f9389ec1b,https://host.ru/f1eb4601740d627ab0,Russia,32ebb20c13,paid,1
18935,1550094308,e8cf2eb8e6,https://host.ru/a5dda93e70318570c0,Belarus,b85baa8c73,yandex,1
18936,1550094314,79530b9a67,https://host.ru/6fda01ec57f23abc9e,Russia,e154b06121,paid,1
18937,1550094323,b3b634f824,https://host.ru/39fa884393666d45fc,Russia,7d27a58fb8,email,1

In [40]:
#Фильтр и действие с помощью loc
#Добавит столюец VAT и значения только если выполняется условие, иначе NaN

log.loc[log['region'] == 'Russia', 'VAT'] = 1.2
log.sample(10)

,timestamp,visit_id,url,region,user_id,traffic_source,new,VAT
7840,1550027689,f96b50dcb4,https://host.ru/da83c74e35e7806fe0,Ukraine,55f98c1ae4,google,1,NaN
12762,1550056871,caa13e63e2,https://host.ru/ac2d98a5a63e7c6e28,Belarus,0667ea1e74,direct,1,NaN
3619,1550002401,5b73d5cf70,https://host.ru/8fe7c39e5c598bbc54,Russia,ee2184d172,yandex,1,1.2
10772,1550044964,ec2a9cfdc7,https://host.ru/2fcb223266880ccf57,Ukraine,a7f41af806,yandex,1,NaN
7490,1550025532,8a2347fce8,https://host.ru/5301a605bd574af1a5,Russia,4b19d92c48,yandex,1,1.2
9678,1550038486,ccadc973ea,https://host.ru/fd32c3d2de55949865,Russia,5c68dcc751,direct,1,1.2
18857,1550093889,c2a2d096cf,https://host.ru/2fcb223266880ccf57,Russia,56e1c55c3e,paid,1,1.2
10419,1550042915,0d2795ed18,https://host.ru/53b1649b8344e663e9,Russia,af01c983e1,direct,1,1.2
418,1549983244,8fdfd77a48,https://host.ru/6407d4271d7b23cdf5,Russia,4049b739e6,paid,1,1.2
15149,1550071257,56d96863e3,https://host.ru/b8b58337d272ee7b15,Ukraine,567ea1c651,yandex,1,NaN

In [41]:
#Lambda функции
#Здесь просто фильтр

print('before lambda')
print(log.count(),end='\n\n')

#попадет все, для чего лямбда = True
log.loc[lambda row: row['region'] == 'Russia'].info()

before lambda
timestamp         18938
visit_id          18938
url               18938
region            18938
user_id           18938
traffic_source    18938
new               18938
VAT               10913
dtype: int64

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10913 entries, 0 to 18937
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       10913 non-null  int64
 1   visit_id        10913 non-null  object
 2   url             10913 non-null  object
 3   region          10913 non-null  object
 4   user_id         10913 non-null  object
 5   traffic_source  10913 non-null  object
 6   new             10913 non-null  int64
 7   VAT             10913 non-null  float64
dtypes: float64(1), int64(2), object(5)
memory usage: 767.3+ KB

In [42]:
#Вурнуть все через лямбда, просто пример
log.loc[lambda row: row.iloc[:,1] == row.iloc[:,1]]

,timestamp,visit_id,url,region,user_id,traffic_source,new,VAT
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,1,1.2
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,1,1.2
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,1,1.2
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,1,1.2
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,1,1.2
...,...,...,...,...,...,...,...,...
18933,1550094288,57e5ba8560,https://host.ru/c2382eb3d6afc8d0f3,Belarus,98b19810d0,paid,1,NaN
18934,1550094296,6f9389ec1b,https://host.ru/f1eb4601740d627ab0,Russia,32ebb20c13,paid,1,1.2
18935,1550094308,e8cf2eb8e6,https://host.ru/a5dda93e70318570c0,Belarus,b85baa8c73,yandex,1,NaN
18936,1550094314,79530b9a67,https://host.ru/6fda01ec57f23abc9e,Russia,e154b06121,paid,1,1.2
18937,1550094323,b3b634f824,https://host.ru/39fa884393666d45fc,Russia,7d27a58fb8,email,1,1.2

In [43]:
log.sample(5)

,timestamp,visit_id,url,region,user_id,traffic_source,new,VAT
12253,1550053948,94e1c8f3c8,https://host.ru/1be58f19f26458f2fe,Russia,0ed6b3cfef,paid,1,1.2
1518,1549989718,81d15e6b91,https://host.ru/87010dbb42ea270213,Russia,3dc41e9de7,direct,1,1.2
8050,1550028890,47e1ad9a6a,https://host.ru/1a0fe145099b114845,Russia,afbc4db2d8,email,1,1.2
6608,1550020335,a9fda0334f,https://host.ru/a8ce0b447c10a1deaa,Ukraine,0f5ff4b758,email,1,NaN
8113,1550029202,fb0e7f54e9,https://host.ru/a8ce0b447c10a1deaa,Russia,a0f8259e3f,email,1,1.2

In [44]:
%%time
#Еще фильтры, не через loc (медленно)
#Не забываем про axis = 1!!!

log['Russia_time_stamp_lambda'] = log.apply(lambda row: row['timestamp'] if 'Russia' in row['region'] else None, axis = 1)
log.sample(10)

Wall time: 265 ms

,timestamp,visit_id,url,region,user_id,traffic_source,new,VAT,Russia_time_stamp_lambda
18615,1550092388,45fcdcada8,https://host.ru/3c19b4ef7371864fa3,Ukraine,f1e3a4f9ec,paid,1,NaN,NaN
17117,1550083204,a4c1d6bf98,https://host.ru/05e41944dd85a900a6,Russia,beeec91f25,yandex,1,1.2,1.550083e+09
8496,1550031497,e616feaaa7,https://host.ru/ee7c4e0674a284ee3f,Russia,ef89423ca3,paid,1,1.2,1.550031e+09
10282,1550042119,6f812de334,https://host.ru/53b1649b8344e663e9,Australia,7ada6339e3,google,1,NaN,NaN
11283,1550048124,85141a1ddb,https://host.ru/108ce4b365afb7b88e,Belarus,405ffa4cd8,direct,1,NaN,NaN
14269,1550065913,20e7ec058b,https://host.ru/a5dda93e70318570c0,Russia,76543ec756,direct,1,1.2,1.550066e+09
15527,1550073582,1bc39db24d,https://host.ru/87010dbb42ea270213,Russia,5a89eac601,direct,1,1.2,1.550074e+09
16202,1550077617,d92148c7cf,https://host.ru/f1eb4601740d627ab0,Belarus,e458982d53,direct,1,NaN,NaN
7160,1550023666,a63cb6a1f3,https://host.ru/6407d4271d7b23cdf5,Russia,27ba1108f6,google,1,1.2,1.550024e+09
16336,1550078458,89d3dcd015,https://host.ru/108ce4b365afb7b88e,Russia,51116dac28,yandex,1,1.2,1.550078e+09

In [45]:
%%time
#Тоже самое но через loc

log['Russia_time_stamp_loc'] = log.loc[log['region'].str.contains('Russia'),'timestamp']
log.head()

Wall time: 10 ms

,timestamp,visit_id,url,region,user_id,traffic_source,new,VAT,Russia_time_stamp_lambda,Russia_time_stamp_loc
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,1,1.2,1.549981e+09,1.549981e+09
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,1,1.2,1.549981e+09,1.549981e+09
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,1,1.2,1.549981e+09,1.549981e+09
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,1,1.2,1.549981e+09,1.549981e+09
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,1,1.2,1.549981e+09,1.549981e+09

In [53]:
#isin
#только полное совпадение
#в ответе не будет яндекса

log.loc[log['traffic_source'].isin(['ya','google'])]

,timestamp,visit_id,url,region,user_id,traffic_source,new,VAT,Russia_time_stamp_lambda,Russia_time_stamp_loc,date,hour
11,1549980785,71b6c1d538,https://host.ru/c8d9213a31839f9a3a,Ukraine,3b13701488,google,1,NaN,NaN,NaN,2019-02-12 14:13:05,14
16,1549980801,374708fff7,https://host.ru/39fa884393666d45fc,Russia,e9bd59e22d,google,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:13:21,14
21,1549980823,c90232586b,https://host.ru/da83c74e35e7806fe0,Ukraine,a00405d70c,google,1,NaN,NaN,NaN,2019-02-12 14:13:43,14
46,1549980969,878f32f76b,https://host.ru/186c4d6b47dbde0e74,Russia,ee82681887,google,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:16:09,14
51,1549981001,8e8fe47e4a,https://host.ru/39fa884393666d45fc,Ukraine,8aa7273421,google,1,NaN,NaN,NaN,2019-02-12 14:16:41,14
...,...,...,...,...,...,...,...,...,...,...,...,...
18902,1550094117,3d95211bef,https://host.ru/c2382eb3d6afc8d0f3,Russia,03554d20d2,google,1,1.2,1.550094e+09,1.550094e+09,2019-02-13 21:41:57,21
18910,1550094158,7edb76ff7d,https://host.ru/c2382eb3d6afc8d0f3,Ukraine,2172fd3d5c,google,1,NaN,NaN,NaN,2019-02-13 21:42:38,21
18915,1550094190,9133d16538,https://host.ru/87010dbb42ea270213,Ukraine,fda7aa4fe9,google,1,NaN,NaN,NaN,2019-02-13 21:43:10,21
18926,1550094236,098c3666b2,https://host.ru/b8b58337d272ee7b15,Ukraine,1dfd030cba,google,1,NaN,NaN,NaN,2019-02-13 21:43:56,21
18932,1550094280,5001544772,https://host.ru/9f90e5c423a5f976d4,Russia,072148e3ba,google,1,1.2,1.550094e+09,1.550094e+09,2019-02-13 21:44:40,21

In [56]:
#в то время как str.contains это проверка на содержание подстроки
#в ответе будет yandex
log.loc[log['traffic_source'].str.contains('ya|google')]

,timestamp,visit_id,url,region,user_id,traffic_source,new,VAT,Russia_time_stamp_lambda,Russia_time_stamp_loc,date,hour
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:11:32,14
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:11:55,14
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:12:05,14
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:12:16,14
5,1549980742,8855508aad,https://host.ru/df646c3676cc259fa0,Russia,fc43898e47,yandex,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:12:22,14
...,...,...,...,...,...,...,...,...,...,...,...,...
18919,1550094214,6da87e20bd,https://host.ru/39fa884393666d45fc,China,a8ba7ec720,yandex,1,NaN,NaN,NaN,2019-02-13 21:43:34,21
18926,1550094236,098c3666b2,https://host.ru/b8b58337d272ee7b15,Ukraine,1dfd030cba,google,1,NaN,NaN,NaN,2019-02-13 21:43:56,21
18928,1550094255,c7e4bce62a,https://host.ru/8880fd00cf23066541,Australia,e721d23ec6,yandex,1,NaN,NaN,NaN,2019-02-13 21:44:15,21
18932,1550094280,5001544772,https://host.ru/9f90e5c423a5f976d4,Russia,072148e3ba,google,1,1.2,1.550094e+09,1.550094e+09,2019-02-13 21:44:40,21
18935,1550094308,e8cf2eb8e6,https://host.ru/a5dda93e70318570c0,Belarus,b85baa8c73,yandex,1,NaN,NaN,NaN,2019-02-13 21:45:08,21

In [46]:
#Пустые значения
import numpy as np

data = pd.DataFrame({'name':['Moscow', np.NAN, np.NAN, np.nan, 'others']})
data.head()

     name
0  Moscow
1     NaN
2     NaN
3     NaN
4  others

In [47]:
#Фильтр на пустые

data.loc[pd.isnull(data['name'])]

  name
1  NaN
2  NaN
3  NaN

In [48]:
#наоборот
data.loc[~pd.isnull(data['name'])].head()

     name
0  Moscow
4  others

In [49]:
#Дата

log['date'] = pd.to_datetime(log['timestamp'],unit = 's')
log.head()

,timestamp,visit_id,url,region,user_id,traffic_source,new,VAT,Russia_time_stamp_lambda,Russia_time_stamp_loc,date
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:11:32
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:11:44
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:11:55
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:12:05
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:12:16

In [50]:
#Работа с датой
log['hour'] = log['date'].dt.hour

log.head()

,timestamp,visit_id,url,region,user_id,traffic_source,new,VAT,Russia_time_stamp_lambda,Russia_time_stamp_loc,date,hour
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:11:32,14
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:11:44,14
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:11:55,14
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:12:05,14
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,1,1.2,1.549981e+09,1.549981e+09,2019-02-12 14:12:16,14